version: "3"
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data_prod:/data/db
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.api
    ports:
      - "4000:4000"
    volumes:
      - ./:/home/node/bookingeek
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.app
    ports:
      - "5173:5173"
    volumes:
      - ./:/home/node/bookingeek
  storybook:
    build:
      context: ./
      dockerfile: ./Dockerfile.storybook
    ports:
      - "6006:6006"
    volumes:
      - ./:/home/node/bookingeek
  website:
    build:
      context: ./
      dockerfile: ./Dockerfile.website
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/bookingeek
volumes:
  mongo-data_prod:
    external: false
