version: "3"
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data_prod:/data/db
  backend:
    build: ./apps/bookingeek-api
    ports:
      - "3000:3000"
    volumes:
      - ./apps/bookingeek-api/src:/home/node/bookingeek-api/src
  frontend:
    build: ./apps/bookingeek-app
    ports:
      - "5173:5173"
    volumes:
      - ./apps/bookingeek-app/src:/home/node/bookingeek-app/src
      - ./apps/bookingeek-app/public:/home/node/bookingeek-app/public
volumes:
  mongo-data_prod:
    external: false
